# Generated by Django 4.2.6 on 2023-10-18 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Item slug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Item title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='Item URL'),
        ),
    ]
