# Generated by Django 4.2.6 on 2023-10-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_item_parent_alter_item_slug_alter_item_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Item URL'),
        ),
    ]
