# Generated by Django 4.2.6 on 2023-10-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_remove_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_submenu_open',
            field=models.BooleanField(default=False),
        ),
    ]
