# Generated by Django 4.2.6 on 2023-10-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_item_is_submenu_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_submenu_open',
        ),
    ]
